# Generated by Django 5.1.7 on 2025-04-27 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LifeStory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('is_complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('emotions', models.ManyToManyField(blank=True, related_name='life_stories', to='main.emotion')),
                ('events', models.ManyToManyField(blank=True, related_name='life_stories', to='main.event')),
                ('locations', models.ManyToManyField(blank=True, related_name='life_stories', to='main.location')),
                ('people', models.ManyToManyField(blank=True, related_name='life_stories', to='main.person')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='life_stories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Life Stories',
            },
        ),
    ]
