# Generated by Django 5.1.7 on 2025-04-28 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_lifestory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='attached_memories',
        ),
        migrations.DeleteModel(
            name='Memory',
        ),
    ]
